# Generated by Django 3.1.7 on 2021-03-03 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='student',
        ),
        migrations.RemoveField(
            model_name='warden',
            name='warden',
        ),
        migrations.AddField(
            model_name='room',
            name='name',
            field=models.CharField(default='G1', max_length=10),
        ),
    ]
