# Generated by Django 3.1.7 on 2021-03-03 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_auto_20210303_0943'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='vacant',
        ),
        migrations.AlterField(
            model_name='student',
            name='room_allotted',
            field=models.BooleanField(default=True),
        ),
    ]
